function stAgentBiFSPJobMachConfig = fsp_def_struct_bidir_cfg()


stAgentBiFSPJobMachConfig = struct('iTotalForwardJobs', [], ...
    'iTotalReverseJobs', [], ...
    'iOptionPackageIP', [], ...
    'iOptRule', [], ...
    'iTotalMachType', [], ...
    'iPlotFlag', [], ...
    'fTimeUnit_Min', [], ...
    'iCriticalMachType', [], ...
    'iReleaseTimeSlotGlobal', []);
