function fsp_save_one_per_srch_fig(stBerthJobInfo)

iPathStringList = strfind(stBerthJobInfo.strInputFilename, '\');
strPathName = stBerthJobInfo.strInputFilename(1:iPathStringList(end));

figure(10)
saveas(gcf, strcat(strPathName, 'SumCostMat_Ag1.jpg'), 'jpg')
figure(20)
saveas(gcf, strcat(strPathName, 'SumCostMat_Ag2.jpg'), 'jpg')
figure(30)
saveas(gcf, strcat(strPathName, 'SumCostMat_Ag3.jpg'), 'jpg')
figure(40)
saveas(gcf, strcat(strPathName, 'SumCostMat_Ag4.jpg'), 'jpg')
figure(11)
saveas(gcf, strcat(strPathName, 'PenaltyMat_Ag1.jpg'), 'jpg')
figure(21)
saveas(gcf, strcat(strPathName, 'PenaltyMat_Ag2.jpg'), 'jpg')
figure(31)
saveas(gcf, strcat(strPathName, 'PenaltyMat_Ag3.jpg'), 'jpg')
figure(41)
saveas(gcf, strcat(strPathName, 'PenaltyMat_Ag4.jpg'), 'jpg')
figure(12)
saveas(gcf, strcat(strPathName, 'MakespanMat_Ag1.jpg'), 'jpg')
figure(22)
saveas(gcf, strcat(strPathName, 'MakespanMat_Ag2.jpg'), 'jpg')
figure(32)
saveas(gcf, strcat(strPathName, 'MakespanMat_Ag3.jpg'), 'jpg')
figure(42)
saveas(gcf, strcat(strPathName, 'MakespanMat_Ag4.jpg'), 'jpg')
figure(13)
saveas(gcf, strcat(strPathName, 'ResourceCostMat_Ag1.jpg'), 'jpg')
figure(23)
saveas(gcf, strcat(strPathName, 'ResourceCostMat_Ag2.jpg'), 'jpg')
figure(33)
saveas(gcf, strcat(strPathName, 'ResourceCostMat_Ag3.jpg'), 'jpg')
figure(43)
saveas(gcf, strcat(strPathName, 'ResourceCostMat_Ag4.jpg'), 'jpg')