function [stQuayCraneJobList, stContainerDischargeJobSequence, stContainerLoadJobSequence] = jsp_def_struct_port_job_list()
% History
% YYYYMMDD  Notes
% 20080322  Add iReleaseTimeSlotGlobal

stContainerDischargeJobSequence = struct('fCycleTimeMachineType1', [], ...
    'Time_PM', [], ...
    'Time_YC', [], ...
    'YC_Id', [], ...
    'PM_Id', [], ...
    'QC_Id', [], ...
    'Time_PM_YC', []);

stContainerLoadJobSequence = struct('fCycleTimeMachineType1', [], ...
    'Time_PM', [], ...
    'Time_YC', [], ...
    'YC_Id', [], ...
    'PM_Id', [], ...
    'QC_Id', [], ...
    'Time_PM_YC', []);
stQuayCraneJobList = struct('strJobListInputFilename', [], ...
                        'iAlgoOption', [], ...
                      'fTimeUnit_Min', [], ...
                           'iOptRule', [], ...
           'TotalContainer_Discharge', [], ...
               'MaxVirtualPrimeMover', [], ...
                'MaxVirtualYardCrane', [], ...
                'TotalContainer_Load', [], ...
    'stContainerDischargeJobSequence', stContainerDischargeJobSequence, ...
         'stContainerLoadJobSequence', stContainerLoadJobSequence, ...
                   'stResourceConfig', [], ...
                          'iPlotFlag', [], ...
                          'iReleaseTimeSlotGlobal', 0); % not load from file
